"""
Feedback subpackage - Dynamic feedback widget generation.
"""

from gchat.card_builder.feedback.components import (
    BUTTON_TYPES,
    CLICKABLE_COMPONENTS,
    DUAL_COMPONENTS,
    LAYOUT_WRAPPERS,
    SECTION_STYLES,
    TEXT_COMPONENTS,
)
from gchat.card_builder.feedback.dynamic import (
    DynamicFeedbackBuilder,
    get_dynamic_feedback_builder,
)
from gchat.card_builder.feedback.icons import (
    FEEDBACK_ICONS,
    FEEDBACK_MATERIAL_ICONS,
    NEGATIVE_ICONS,
    NEGATIVE_IMAGE_URLS,
    NEGATIVE_MATERIAL_ICONS,
    POSITIVE_ICONS,
    POSITIVE_IMAGE_URLS,
    POSITIVE_MATERIAL_ICONS,
)
from gchat.card_builder.feedback.prompts import (
    CONTENT_FEEDBACK_PROMPTS,
    FEEDBACK_COLORS,
    FEEDBACK_TEXT_STYLES,
    FORM_FEEDBACK_PROMPTS,
    NEGATIVE_LABELS,
    POSITIVE_LABELS,
)
from gchat.card_builder.feedback.registries import (
    CLICK_CONFIGS,
    LAYOUT_CONFIGS,
    TEXT_CONFIGS,
)
from gchat.card_builder.feedback.widgets import (
    apply_button_icon,
    build_clickable_feedback,
    build_clickable_item,
    build_feedback_button_item,
    build_feedback_chip_item,
    build_feedback_layout,
    build_feedback_widget,
    build_styled_feedback_prompt,
    build_text_feedback,
    click_button_list,
    click_chip_list,
    click_emoji_rating,
    click_icon_buttons,
    click_icon_buttons_alt,
    click_star_rating,
    click_url_image_buttons,
    create_feedback_section,
    dual_columns_inline,
    dual_decorated_inline_only,
    dual_decorated_with_button,
    get_feedback_base_url,
    layout_compact,
    layout_sequential,
    layout_with_divider,
    make_callback_url,
    resolve_config_icon,
    style_feedback_keyword,
    text_chip,
    text_decorated,
    text_decorated_icon,
    text_decorated_labeled,
    text_paragraph,
)

__all__ = [
    # Dynamic feedback builder
    "DynamicFeedbackBuilder",
    "get_dynamic_feedback_builder",
    # Prompts and labels
    "CONTENT_FEEDBACK_PROMPTS",
    "FORM_FEEDBACK_PROMPTS",
    "FEEDBACK_TEXT_STYLES",
    "FEEDBACK_COLORS",
    "POSITIVE_LABELS",
    "NEGATIVE_LABELS",
    # Icons
    "POSITIVE_MATERIAL_ICONS",
    "NEGATIVE_MATERIAL_ICONS",
    "FEEDBACK_MATERIAL_ICONS",
    "POSITIVE_ICONS",
    "NEGATIVE_ICONS",
    "FEEDBACK_ICONS",
    "POSITIVE_IMAGE_URLS",
    "NEGATIVE_IMAGE_URLS",
    # Component categories
    "TEXT_COMPONENTS",
    "CLICKABLE_COMPONENTS",
    "DUAL_COMPONENTS",
    "LAYOUT_WRAPPERS",
    "BUTTON_TYPES",
    "SECTION_STYLES",
    # Config registries
    "CLICK_CONFIGS",
    "TEXT_CONFIGS",
    "LAYOUT_CONFIGS",
    # Widget builders (from widgets.py)
    "get_feedback_base_url",
    "make_callback_url",
    "build_feedback_widget",
    "style_feedback_keyword",
    "build_styled_feedback_prompt",
    "build_text_feedback",
    "text_paragraph",
    "text_decorated",
    "text_decorated_icon",
    "text_decorated_labeled",
    "text_chip",
    "build_clickable_item",
    "apply_button_icon",
    "build_feedback_button_item",
    "build_feedback_chip_item",
    "resolve_config_icon",
    "build_clickable_feedback",
    "click_button_list",
    "click_chip_list",
    "click_icon_buttons",
    "click_icon_buttons_alt",
    "click_url_image_buttons",
    "click_star_rating",
    "click_emoji_rating",
    "dual_decorated_with_button",
    "dual_decorated_inline_only",
    "dual_columns_inline",
    "build_feedback_layout",
    "layout_sequential",
    "layout_with_divider",
    "layout_compact",
    "create_feedback_section",
]
